language: csharp
sudo: required
mono: none
dotnet: 3.1.102
dist: trusty
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE tester;" -U postgres
  - psql -c "CREATE USER migrator WITH PASSWORD 'postgres';" -U postgres
  - psql -c 'CREATE SCHEMA "public" AUTHORIZATION migrator;' -U postgres -d tester
  - dotnet restore
script:
  - dotnet test ./Tests/Tester.Tests.Unit -c Release -f netcoreapp2.0